# Generated by Django 4.2.11 on 2025-03-04 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes', verbose_name='Duration')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, unique=True, verbose_name='Seat Number')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Booked')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Booking Date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.movie')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.seat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
